name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      - name: Setup Node.js 18.x
        uses: actions/setup-node@master
        with:
          node-version: '18.x'
          
      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Set Config
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-hongkong.aliyuncs.com
          access-key-id: ${{ secrets.OSS_KEY }}
          access-key-secret: ${{ secrets.OSS_SECRET }}

      - name: Delete Files
        run: |
          ossutil rm -rf oss://arknights-toolbox-data/
      
      - name: Upload Files
        run: |
          ossutil cp -j 200 -rf dist/ oss://arknights-toolbox-data/  --meta=Cache-Control:max-age=3600